<a href="https://colab.research.google.com/github/DevAnand-debugger/Numpy_EDA_tools/blob/main/edatools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Name=Dev Anand

###PRN=25070123039

###Batch=A2

####Experiment-8

Tools for EDA-Studhy of Numbpy library

In [ ]:
#Why Numpy?
#Used for mathematical computation
#Base for Pandas

In [ ]:
import numpy as np
a = np.array([10,20,30,40])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

[10 20 30 40]
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
#dimension of array
print(b.shape)

(2, 3)


In [ ]:
print(a.shape) #in one dimension it gives the total number of elements

(4,)


In [ ]:
#to find about the data type
a.dtype

dtype('int64')

In [ ]:
b.dtype

dtype('int64')

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.arange(1,10,2)



array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
c=a*2
d=a+5
print(c)
print(d)

[20 40 60 80]
[15 25 35 45]


In [ ]:
print(a+5)

[15 25 35 45]


In [ ]:
np.mean(a)

np.float64(25.0)

In [ ]:
np.median(a)

np.float64(25.0)

In [ ]:
np.max(a)

np.int64(40)

In [ ]:
np.mean(b)

np.float64(3.5)

In [ ]:
np.median(b)

np.float64(3.5)

In [ ]:
np.min(a)

np.int64(15)

In [ ]:
np.sum(a)

np.int64(100)